# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(764, 630)
        MainWindow.setStyleSheet("background-color:#63db6f")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(160, 40, 431, 451))
        self.frame.setTabletTracking(False)
        self.frame.setAcceptDrops(False)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("color: black\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(13)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(100, 40, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLineWidth(3)
        self.label.setObjectName("label")
        self.cb_numbers = QtWidgets.QCheckBox(self.frame)
        self.cb_numbers.setGeometry(QtCore.QRect(110, 240, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_numbers.setFont(font)
        self.cb_numbers.setAutoFillBackground(False)
        self.cb_numbers.setObjectName("cb_numbers")
        self.cb_alphabet = QtWidgets.QCheckBox(self.frame)
        self.cb_alphabet.setGeometry(QtCore.QRect(110, 270, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_alphabet.setFont(font)
        self.cb_alphabet.setStyleSheet("")
        self.cb_alphabet.setObjectName("cb_alphabet")
        self.btn_generate = QtWidgets.QPushButton(self.frame)
        self.btn_generate.setGeometry(QtCore.QRect(100, 320, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_generate.setFont(font)
        self.btn_generate.setStyleSheet("color: black;\n"
"background-color:#0cc71f;\n"
"border-radius: 8px;\n"
"border: 2px solid black")
        self.btn_generate.setObjectName("btn_generate")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(100, 120, 221, 41))
        self.frame_2.setStyleSheet("background: white")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(4)
        self.frame_2.setObjectName("frame_2")
        self.result = QtWidgets.QLineEdit(self.frame_2)
        self.result.setGeometry(QtCore.QRect(32, 10, 161, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.result.setFont(font)
        self.result.setFrame(False)
        self.result.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.result.setCursorPosition(18)
        self.result.setDragEnabled(False)
        self.result.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.result.setClearButtonEnabled(False)
        self.result.setObjectName("result")
        self.spinBox = QtWidgets.QSpinBox(self.frame)
        self.spinBox.setGeometry(QtCore.QRect(330, 130, 42, 22))
        self.spinBox.setStyleSheet("background: white")
        self.spinBox.setObjectName("spinBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 764, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Генератор паролів"))
        self.cb_numbers.setText(_translate("MainWindow", "Використати чиcла"))
        self.cb_alphabet.setText(_translate("MainWindow", "Використати алфавіт"))
        self.btn_generate.setText(_translate("MainWindow", "Згенерувати"))
        self.result.setText(_translate("MainWindow", "Тут буде результат"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
